networks:
  inception:
    name: "inception"
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wordpress:
    file: ../secrets/wordpress.txt
  mariadb:
    file: ../secrets/mariadb.txt
  ssl_config:
    file: ../secrets/ssl_config.txt

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind    
      device: ${HOME}/ulyildiz/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/ulyildiz/data/wordpress

services:
  mariadb:
    container_name: mariadb
    build: ./Containers/MariaDB
    image: srcs_mariadb:notlatest
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - 3306
    secrets:
      - db_password
      - db_root_password
      - mariadb

  wordpress:
    container_name: wordpress
    build: ./Containers/WordPress
    image: srcs_wordpress:notlatest
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    expose:
      - 9000
    env_file:
      - ./Containers/WordPress/.env
    secrets:
      - db_password
      - wordpress
      - mariadb
    depends_on:
      - mariadb
  
  nginx:
    container_name: nginx
    build: ./Containers/NGINX
    image: srcs_nginx:notlatest
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    env_file:
      - ./Containers/NGINX/.env
    secrets:
      - ssl_config
    depends_on:
      - mariadb
      - wordpress