user	www;
worker_processes auto;
pid /run/nginx.pid;

error_log /var/log/nginx/error.log warn;

include /etc/nginx/modules/*.conf;

events {
	worker_connections 1024;
	use epoll;
	multi_accept on;
}

http {
	# Basic Settings
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	server_tokens off;

	# MIME Types
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	# Logging Settings
	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
					'$status $body_bytes_sent "$http_referer" '
					'"$http_user_agent" "$http_x_forwarded_for"';
	
	access_log /var/log/nginx/access.log main;

	# Gzip Settings
	gzip on;
	gzip_vary on;
	gzip_proxied any;
	gzip_comp_level 6;
	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	# Virtual Host Configs
	include /etc/nginx/http.d/*.conf;
}
