user	www;

worker_processes auto;
error_log /var/log/nginx/error.log warn;
pcre_jit on;

include /etc/nginx/modules/*.conf;

events {
	worker_connections 1024;
}

http {
	
	ssl_protocols TLSv1.2 TLSv1.3;
	
	server {
		server_name login;
		listen 443 ssl;

		ssl_certificate !KEY!;
		ssl_certificate_key !CERT!;
		
		root /var/www/html;

		location ~\.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_index   index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}	
	}
}
